add hierarchical configuration entities:
  title: 'Create new Hierarchical configuration entities'

administer hierarchical configuration entities:
  title: 'Administer Hierarchical configuration entities'
  description: 'Allow to access the administration form to configure Hierarchical configuration entities.'
  restrict access: true

delete hierarchical configuration entities:
  title: 'Delete Hierarchical configuration entities'

edit hierarchical configuration entities:
  title: 'Edit Hierarchical configuration entities'

view published hierarchical configuration entities:
  title: 'View published Hierarchical configuration entities'

view unpublished hierarchical configuration entities:
  title: 'View unpublished Hierarchical configuration entities'
