entity.hierarchical_configuration_type.add_form:
  route_name: 'entity.hierarchical_configuration_type.add_form'
  title: 'Add Hierarchical configuration bundle'
  appears_on:
    - entity.hierarchical_configuration_type.collection

