# Hierarchical configuration type menu items definition
entity.hierarchical_configuration_type.collection:
  title: 'Hierarchical configuration'
  route_name: entity.hierarchical_configuration_type.collection
  description: 'List Hierarchical configuration bundles'
  parent: system.admin_structure
  weight: 99

