hierarchical_config.hierarchical_configuration_type.*:
  type: config_entity
  label: 'Hierarchical configuration type config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
